# mingw environment to build dependency binaries in a reproducible environment
# https://wiki.debian.org/ReproducibleBuilds

pyinstaller:
  build: pyinstaller
  volumes:
# bitmask sources
    - ../../:/var/src/bitmask:ro
# produced binaries
    - ../../build:/var/build
openvpn:
  build: openvpn
  volumes:
# produced binaries
    - ../../build:/var/build

# nsis environment to build installer (exe) that contains all required binaries
# for a clean, just installed windows machine
installer:
  build: installer
  volumes:
# bitmask sources
    - ../../:/var/src/bitmask:ro
# produced installers - configured in bitmask.nsh
    - ../../dist:/var/dist
